### ISSUE TITLE
Unable to load the project

### ISSUE THREAD

**Issue by stefanlam88** [ywng/fundvis#1]
Hi developer, 
       I m facing issue here. I have downloaded your application. Then I try load in my browser and see. It prompts many error that some javasript is undefined. any conf I have to set? I had checked all the js was included. any opinion?

**Comment by ywng** [comment]
If u didn't change any code (& run it on a server, not localhost),
It should be fine
But if you change the code, made sure the order of the js file loaded is right
Or you can modify it into a "document ready style"
Read this article, if you want to know more about js loading problems
http://coolshell.cn/articles/9749.html

I guess you should know that
JS files run once they are arrived. That's why something is undefined if it is not loaded beforehead.

Hope that I can answer your concerns

## 

Jason NG Yik-wai
Dual Degree Program in Technology and Management
The Hong Kong University of Science and Technology
victor.not.to.yield@gmail.commailto:victor.not.to.yield@gmail.com
(852) 5420-3135

On 2014?7?3?, at 17:11, "stefanlam88" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi developer,
I m facing issue here. I have downloaded your application. Then I try load in my browser and see. It prompts many error that some javasript is undefined. any conf I have to set? I had checked all the js was included. any opinion?

##

**Comment by stefanlam88** [comment]
Hi I have just downloaded the src, then i simply run the page JPMProvident.html. but it shows me js undefine. I no touch any js order. Your can work?

**Comment by ywng** [comment]
ic, the program cannot run locally (it must be on a server) because of the reason:
1. AJAX request to my api fetching the data for the graph cannot be "cross origin" (in fund.js _init_funds(url) {.....}  )

search about it if you don't know what's cross origin

So, run it in some server hosting php, like "OpenShift".

I am sorry that my project is not easy to replicate.
If you just need the D3/ graphic part, actually you just need to make your own data source.
I know that you need to understand the structure of the data in order to change into the way that you want. For this purpose, you can just open the chrome debugger, see the preview response of the AJAX request "getAllPriceJPMORSO".
![screen shot 2014-07-04 at 1 17 47](https://cloud.githubusercontent.com/assets/1456563/3473283/662635de-02d6-11e4-81dd-a2305e8d10a7.png)

if you change the structure of the data, pls change accordingly the d3 / html code .

## 

Jason NG Yik-wai
Dual Degree Program in Technology and Management
The Hong Kong University of Science and Technology
victor.not.to.yield@gmail.commailto:victor.not.to.yield@gmail.com
(852) 5420-3135

On 2014年7月3日, at 18:20, "stefanlam88" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi I have just downloaded the src, then i simply run the page JPMProvident.html. but it shows me js undefine. I no touch any js order. Your can work?

**Comment by stefanlam88** [comment]
Thanks I remove cross browser origin and it works perfectly. thanks man

**Comment by stefanlam88** [comment]
If I wanna hardcore data I can hardcode with json data in .json and call it locally right?

**Comment by ywng** [comment]
Yeah, I have tried, the problem is cross origin.
For you to load the json file locally, I remember, there is still some settings in the browser that you need to change. 

For knowing the data structure of my original data, as I have said, go to the debugger to have a preview in the AJAX call result, the json data is parsed in a nice way for you 

I am sorry that the code right now are not well documented at this moment because I am still working on it.
